# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_allocation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis saat alokasi diajukan.', max_length=100, null=True, unique=True),
        ),
    ]
