# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0002_add_completed_by_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis saat recall diajukan.', max_length=100, null=True, unique=True),
        ),
    ]
