# Generated by Django 6.0.4 on 2026-07-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0007_therapeuticclass_item_therapeutic_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('contract_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('CLOSED', 'Ditutup')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_procurement_contracts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_procurement_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procurement_contracts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_procurement_contracts', to=settings.AUTH_USER_MODEL)),
                ('sumber_dana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_contracts', to='items.fundingsource')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_contracts', to='items.supplier')),
            ],
            options={
                'db_table': 'procurement_contracts',
                'ordering': ['-contract_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('amendment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_procurement_amendments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procurement_amendments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_procurement_amendments', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='procurement.procurementcontract')),
            ],
            options={
                'db_table': 'procurement_amendments',
                'ordering': ['-amendment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.procurementcontract')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_contract_lines', to='items.item')),
            ],
            options={
                'db_table': 'procurement_contract_lines',
                'ordering': ['item__nama_barang', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAmendmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revised_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revised_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.procurementamendment')),
                ('contract_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendment_lines', to='procurement.procurementcontractline')),
            ],
            options={
                'db_table': 'procurement_amendment_lines',
                'ordering': ['contract_line__item__nama_barang', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='procurementcontract',
            index=models.Index(fields=['status', 'contract_date'], name='idx_proc_contract_status_date'),
        ),
        migrations.AddIndex(
            model_name='procurementamendment',
            index=models.Index(fields=['status', 'amendment_date'], name='idx_proc_amend_status_date'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementcontractline',
            unique_together={('contract', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='procurementamendmentline',
            unique_together={('amendment', 'contract_line')},
        ),
    ]
