# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_procurement_contract_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementamendment',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementcontract',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
