# Generated by Django 6.0.8 on 2026-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_procurementamendment_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcontract',
            name='external_document_number',
            field=models.CharField(blank=True, db_index=True, help_text='Nomor referensi dokumen yang diterbitkan oleh aplikasi lain.', max_length=100),
        ),
    ]
