# Generated by Django 5.1.15 on 2026-02-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_lot', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=2, default=0, help_text='Stock allocated for pending distributions', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='items.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='items.location')),
                ('receiving_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='receiving.receiving')),
                ('sumber_dana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='items.fundingsource')),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['item', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Barang Masuk'), ('OUT', 'Barang Keluar'), ('ADJUST', 'Penyesuaian'), ('RETURN', 'Retur')], max_length=10)),
                ('batch_lot', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_type', models.CharField(choices=[('RECEIVING', 'Penerimaan'), ('DISTRIBUTION', 'Distribusi'), ('ADJUSTMENT', 'Penyesuaian'), ('INITIAL_IMPORT', 'Import Awal')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(default=0, help_text='Polymorphic reference to source document')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='items.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='items.location')),
                ('sumber_dana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='items.fundingsource')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
