# Generated by Django 5.1.15 on 2026-02-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item', 'location', 'expiry_date'], name='idx_stock_fefo'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['expiry_date'], name='idx_stock_expiry'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item', 'location'], name='idx_stock_item_loc'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_stock_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='chk_stock_reserved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('item', 'location', 'batch_lot', 'sumber_dana'), name='uq_stock_batch'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['item', '-created_at'], name='idx_trans_item_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_trans_reference'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='idx_trans_created'),
        ),
    ]
