# Generated by Django 6.0.4 on 2026-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_transaction_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
