# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_unit_price_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis saat mutasi diselesaikan.', max_length=100, null=True, unique=True),
        ),
    ]
