# Generated by Django 6.0.4 on 2026-06-12 02:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_is_essential'),
        ('puskesmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuskesmasSBBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, help_text='Kosongkan untuk auto-generate (SBBK-YYYYMM-XXXXX)', max_length=100, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_puskesmas_sbbks', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_sbbks', to='items.facility')),
            ],
            options={
                'db_table': 'puskesmas_sbbks',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuskesmasSBBKItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Jumlah diterima', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Harga satuan pada SBBK', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_sbbk_items', to='items.item')),
                ('sbbk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='puskesmas.puskesmassbbk')),
            ],
            options={
                'db_table': 'puskesmas_sbbk_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='puskesmassbbk',
            index=models.Index(fields=['facility', 'received_date'], name='idx_sbbk_facility_date'),
        ),
    ]
