# Generated by Django 6.0.4 on 2026-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas', '0002_puskesmassbbk_puskesmassbbkitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puskesmassbbkitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Jumlah diterima dalam satuan utuh', max_digits=12),
        ),
    ]
