# Generated by Django 6.0.4 on 2026-06-12 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_is_essential'),
        ('puskesmas', '0003_alter_puskesmassbbkitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuskesmasConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulan', models.PositiveSmallIntegerField()),
                ('tahun', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_puskesmas_consumptions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_consumptions', to='items.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_puskesmas_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'puskesmas_consumptions',
                'ordering': ['-tahun', '-bulan', 'facility__name'],
            },
        ),
        migrations.CreateModel(
            name='PuskesmasSubunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('subunit_type', models.CharField(choices=[('TREATMENT_ROOM', 'Ruang Tindakan'), ('HELPER_SITE', 'Puskesmas Pembantu')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_subunits', to='items.facility')),
            ],
            options={
                'db_table': 'puskesmas_subunits',
                'ordering': ['facility__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PuskesmasConsumptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='puskesmas.puskesmasconsumption')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_consumption_entries', to='items.item')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_entries', to='puskesmas.puskesmassubunit')),
            ],
            options={
                'db_table': 'puskesmas_consumption_entries',
                'ordering': ['item__kategori__sort_order', 'item__nama_barang', 'subunit__sort_order', 'subunit__name'],
            },
        ),
        migrations.AddIndex(
            model_name='puskesmasconsumption',
            index=models.Index(fields=['facility', 'tahun', 'bulan'], name='idx_pkcons_fac_period'),
        ),
        migrations.AddConstraint(
            model_name='puskesmasconsumption',
            constraint=models.UniqueConstraint(fields=('facility', 'bulan', 'tahun'), name='uq_pkconsumption_facility_period'),
        ),
        migrations.AddIndex(
            model_name='puskesmassubunit',
            index=models.Index(fields=['facility', 'is_active', 'sort_order'], name='idx_pksubunit_facility_active'),
        ),
        migrations.AddConstraint(
            model_name='puskesmassubunit',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='uq_pksubunit_facility_name'),
        ),
        migrations.AddConstraint(
            model_name='puskesmasconsumptionentry',
            constraint=models.UniqueConstraint(fields=('consumption', 'item', 'subunit'), name='uq_pkconsentry_doc_item_subunit'),
        ),
    ]
