# Generated by Django 6.0.4 on 2026-06-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_is_essential'),
        ('puskesmas', '0005_rename_sbbk_to_receipt_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puskesmasreceiptconfirmation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_puskesmas_receipt_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puskesmasreceiptconfirmation',
            name='document_number',
            field=models.CharField(blank=True, help_text='Kosongkan untuk auto-generate (RCVCONF-YYYYMM-XXXXX)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='puskesmasreceiptconfirmation',
            name='facility',
            field=models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_receipt_confirmations', to='items.facility'),
        ),
        migrations.AlterField(
            model_name='puskesmasreceiptconfirmationitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_receipt_confirmation_items', to='items.item'),
        ),
        migrations.AlterField(
            model_name='puskesmasreceiptconfirmationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Harga satuan aktual yang diterima Puskesmas', max_digits=15),
        ),
    ]
