# Generated by Django 6.0.2 on 2026-03-04 02:38

from django.db import migrations, models


def rename_keuangan_to_auditor(apps, schema_editor):
    """Update any existing users with role='KEUANGAN' to 'AUDITOR'."""
    User = apps.get_model('users', 'User')
    updated = User.objects.filter(role='KEUANGAN').update(role='AUDITOR')
    if updated:
        print(f'  Updated {updated} user(s) from KEUANGAN to AUDITOR')


def rename_auditor_to_keuangan(apps, schema_editor):
    """Reverse: rename AUDITOR back to KEUANGAN."""
    User = apps.get_model('users', 'User')
    User.objects.filter(role='AUDITOR').update(role='KEUANGAN')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # First, update existing data
        migrations.RunPython(
            rename_keuangan_to_auditor,
            rename_auditor_to_keuangan,
        ),
        # Then, alter the field choices
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('KEPALA', 'Kepala Instalasi'), ('ADMIN_UMUM', 'Admin Umum'), ('GUDANG', 'Petugas Gudang'), ('AUDITOR', 'Auditor')], default='ADMIN_UMUM', max_length=20),
        ),
    ]
