# Generated by Django 6.0.2 on 2026-03-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_keuangan_to_auditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('users', 'Manajemen User'), ('items', 'Master Barang'), ('stock', 'Stok'), ('receiving', 'Penerimaan'), ('distribution', 'Distribusi'), ('recall', 'Recall / Retur'), ('expired', 'Kadaluarsa'), ('stock_opname', 'Stock Opname'), ('reports', 'Laporan'), ('admin_panel', 'Admin Panel')], max_length=30)),
                ('scope', models.PositiveSmallIntegerField(choices=[(0, 'Tidak Ada'), (1, 'Lihat'), (2, 'Operasional'), (3, 'Persetujuan'), (4, 'Kelola')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Access',
                'verbose_name_plural': 'Module Accesses',
                'db_table': 'user_module_accesses',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
