# Generated by Django 6.0.2 on 2026-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_moduleaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('KEPALA', 'Kepala Instalasi'), ('ADMIN_UMUM', 'Admin Umum'), ('GUDANG', 'Petugas Gudang'), ('AUDITOR', 'Auditor')], default='ADMIN_UMUM', max_length=20, verbose_name='Jabatan'),
        ),
    ]
