# Generated by Django 6.0.4 on 2026-07-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_reconcile_model_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccess',
            name='module',
            field=models.CharField(choices=[('users', 'Manajemen User'), ('items', 'Master Barang'), ('stock', 'Stok'), ('receiving', 'Penerimaan'), ('procurement', 'SPJ / Pengadaan'), ('distribution', 'Distribusi'), ('allocation', 'Alokasi'), ('recall', 'Recall / Retur'), ('expired', 'Kadaluarsa'), ('stock_opname', 'Stock Opname'), ('reports', 'Laporan'), ('admin_panel', 'Admin Panel'), ('puskesmas', 'Permintaan Puskesmas'), ('lplpo', 'LPLPO')], max_length=30),
        ),
    ]
