# Generated by Django 6.0.8 on 2026-09-21 04:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


RULE_DEFAULTS = (
    ('ALLOCATION', 'Alokasi', 'ALK-{year}-{seq}', 'YEARLY', 4),
    ('DISTRIBUTION_LPLPO', 'Distribusi LPLPO', '440/{seq}/SBBK.RF/{year}', 'YEARLY', 1),
    ('DISTRIBUTION_SPECIAL_REQUEST', 'Permintaan Khusus', '440/{seq}/KD.F/{year}', 'YEARLY', 1),
    ('PROCUREMENT_CONTRACT', 'SPJ / Kontrak', 'SPJ-{year}-{seq}', 'YEARLY', 5),
    ('PROCUREMENT_AMENDMENT', 'Amandemen SPJ', '{parent}-A{seq}', 'NEVER', 1),
    ('RECEIVING', 'Penerimaan', 'RCV-{year}-{seq}', 'YEARLY', 5),
    ('RECALL', 'Recall', 'REC-{year}{month}-{seq}', 'MONTHLY', 5),
    ('EXPIRED', 'Kedaluwarsa', 'EXP-{year}{month}-{seq}', 'MONTHLY', 5),
    ('STOCK_TRANSFER', 'Mutasi Lokasi', 'TRF-{year}-{seq}', 'YEARLY', 5),
    ('STOCK_OPNAME', 'Stock Opname', 'SO-{year}{month}-{seq}', 'MONTHLY', 5),
)


def seed_document_number_rules(apps, schema_editor):
    Rule = apps.get_model('core', 'DocumentNumberRule')
    SystemSettings = apps.get_model('core', 'SystemSettings')
    settings_row = SystemSettings.objects.filter(pk=1).first()
    configured_templates = {}
    if settings_row is not None:
        configured_templates = {
            'DISTRIBUTION_LPLPO': settings_row.lplpo_distribution_number_template,
            'DISTRIBUTION_SPECIAL_REQUEST': settings_row.special_request_distribution_number_template,
        }

    for key, label, template, reset_period, padding in RULE_DEFAULTS:
        Rule.objects.update_or_create(
            key=key,
            defaults={
                'label': label,
                'template': configured_templates.get(key) or template,
                'reset_period': reset_period,
                'padding': padding,
            },
        )


def unseed_document_number_rules(apps, schema_editor):
    Rule = apps.get_model('core', 'DocumentNumberRule')
    Rule.objects.filter(key__in=[row[0] for row in RULE_DEFAULTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_systemsettings_distribution_number_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('ALLOCATION', 'Alokasi'), ('DISTRIBUTION_LPLPO', 'Distribusi LPLPO'), ('DISTRIBUTION_SPECIAL_REQUEST', 'Permintaan Khusus'), ('PROCUREMENT_CONTRACT', 'SPJ / Kontrak'), ('PROCUREMENT_AMENDMENT', 'Amandemen SPJ'), ('RECEIVING', 'Penerimaan'), ('RECALL', 'Recall'), ('EXPIRED', 'Kedaluwarsa'), ('STOCK_TRANSFER', 'Mutasi Lokasi'), ('STOCK_OPNAME', 'Stock Opname')], max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=255)),
                ('reset_period', models.CharField(choices=[('NEVER', 'Tidak pernah'), ('YEARLY', 'Tahunan'), ('MONTHLY', 'Bulanan')], default='YEARLY', max_length=10)),
                ('padding', models.PositiveSmallIntegerField(default=1, help_text='Jumlah minimum digit nomor urut.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'db_table': 'document_number_rules',
                'ordering': ['label', 'key'],
            },
        ),
        migrations.RunPython(
            seed_document_number_rules,
            unseed_document_number_rules,
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='lplpo_distribution_number_template',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='special_request_distribution_number_template',
        ),
        migrations.CreateModel(
            name='DocumentNumberIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=100)),
                ('sequence_value', models.PositiveBigIntegerField()),
                ('period_key', models.CharField(blank=True, max_length=6)),
                ('scope_key', models.CharField(blank=True, max_length=191)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('ISSUED', 'Diterbitkan'), ('VOID', 'Dibatalkan')], default='ISSUED', max_length=10)),
                ('object_id', models.PositiveBigIntegerField()),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('rule_label_snapshot', models.CharField(max_length=100)),
                ('template_snapshot', models.CharField(max_length=255)),
                ('reset_period_snapshot', models.CharField(max_length=10)),
                ('padding_snapshot', models.PositiveSmallIntegerField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_numbers_issued', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_numbers_voided', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.documentnumberrule')),
            ],
            options={
                'db_table': 'document_number_issues',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business_date', 'status'], name='idx_doc_issue_date_status'), models.Index(fields=['content_type', 'object_id'], name='idx_doc_issue_target')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'document_number'), name='uq_doc_number_issue_rule_number'), models.UniqueConstraint(fields=('content_type', 'object_id'), name='uq_doc_number_issue_target')],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(blank=True, max_length=6)),
                ('scope_key', models.CharField(blank=True, max_length=191)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='core.documentnumberrule')),
            ],
            options={
                'db_table': 'document_number_sequences',
                'constraints': [models.UniqueConstraint(fields=('rule', 'period_key', 'scope_key'), name='uq_doc_number_sequence_scope')],
            },
        ),
    ]
