# Generated by Django 6.0.8 on 2026-09-28 03:29

from django.db import migrations, models


def repair_backfilled_issuance_metadata(apps, schema_editor):
    database = schema_editor.connection.alias
    Issue = apps.get_model("core", "DocumentNumberIssue")
    ContentType = apps.get_model("contenttypes", "ContentType")

    mappings = (
        ("allocation", "Allocation", "submitted_by_id", "submitted_at"),
        ("procurement", "ProcurementContract", "submitted_by_id", "submitted_at"),
        ("procurement", "ProcurementAmendment", "submitted_by_id", "submitted_at"),
        ("stock", "StockTransfer", "completed_by_id", "completed_at"),
    )
    for app_label, model_name, actor_field, timestamp_field in mappings:
        model = apps.get_model(app_label, model_name)
        content_type = ContentType.objects.db_manager(database).get_for_model(model)
        for obj in model.objects.using(database).all().iterator():
            Issue.objects.using(database).filter(
                content_type_id=content_type.pk,
                object_id=obj.pk,
            ).update(
                issued_by_id=getattr(obj, actor_field, None),
                issued_at=getattr(obj, timestamp_field, None),
            )

    unknown_checkpoint_models = (
        ("distribution", "Distribution"),
        ("receiving", "Receiving"),
        ("recall", "Recall"),
        ("expired", "Expired"),
        ("stock_opname", "StockOpname"),
    )
    for app_label, model_name in unknown_checkpoint_models:
        model = apps.get_model(app_label, model_name)
        content_type = ContentType.objects.db_manager(database).get_for_model(model)
        Issue.objects.using(database).filter(content_type_id=content_type.pk).update(
            issued_by_id=None,
            issued_at=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_repair_backfilled_void_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name="documentnumberissue",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            repair_backfilled_issuance_metadata,
            migrations.RunPython.noop,
        ),
    ]
