# Generated by Django 5.1.15 on 2026-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_type', models.CharField(choices=[('PROCUREMENT', 'Pengadaan'), ('GRANT', 'Hibah')], max_length=20)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('receiving_date', models.DateField()),
                ('grant_origin', models.CharField(blank=True, help_text='Province, Ministry, Donation (for GRANT type)', max_length=100)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi')], default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receivings',
                'ordering': ['-receiving_date'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receiving/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receiving_documents',
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_lot', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receiving_items',
            },
        ),
    ]
