# Generated by Django 5.1.15 on 2026-02-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receivings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiving',
            name='sumber_dana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='items.fundingsource'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Required for PROCUREMENT type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='items.supplier'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_receivings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivingdocument',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='receiving.receiving'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_items', to='items.item'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.receiving'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['status', 'receiving_date'], name='idx_recv_status_date'),
        ),
    ]
