# Generated by Django 5.1.15 on 2026-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
