# Generated by Django 6.0.2 on 2026-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_receiving_approved_at_receiving_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
