# Generated by Django 6.0.2 on 2026-03-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_alter_receiving_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'receiving_type_options',
                'ordering': ['name'],
            },
        ),
    ]
