# Generated by Django 6.0.4 on 2026-06-26 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_therapeuticclass_item_therapeutic_classes'),
        ('receiving', '0008_move_receiving_documents_to_private_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Optional facility reference for receiving documents.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='items.facility'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='receiving_type',
            field=models.CharField(choices=[('PROCUREMENT', 'Pengadaan'), ('GRANT', 'Hibah')], max_length=20),
        ),
    ]
