# Generated by Django 6.0.4 on 2026-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0009_reconcile_model_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='receiving_type',
            field=models.CharField(max_length=20),
        ),
    ]
