# Generated by Django 6.0.4 on 2026-07-02 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('receiving', '0010_alter_receiving_receiving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='procurement.procurementcontract'),
        ),
        migrations.AddField(
            model_name='receivingorderitem',
            name='contract_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_order_items', to='procurement.procurementcontractline'),
        ),
    ]
