# Generated by Django 6.0.4 on 2026-07-02 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_therapeuticclass_item_therapeutic_classes'),
        ('procurement', '0001_initial'),
        ('receiving', '0012_verify_single_planned_receiving_per_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receiving',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False), ('is_planned', True)), fields=('contract',), name='uniq_planned_receiving_contract'),
        ),
    ]
