# Generated by Django 6.0.4 on 2026-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0013_receiving_uniq_planned_receiving_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
