# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0022_backfill_receiving_item_posted_stock_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='import_group',
            field=models.CharField(blank=True, help_text='Identitas grup dari import CSV; bukan nomor dokumen resmi.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis pada checkpoint workflow.', max_length=100, null=True, unique=True),
        ),
    ]
