# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expired', '0003_alter_expired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis saat dokumen diajukan.', max_length=100, null=True, unique=True),
        ),
    ]
