# Generated by Django 5.1.15 on 2026-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_type', models.CharField(choices=[('LPLPO', 'LPLPO'), ('ALLOCATION', 'Alokasi'), ('SPECIAL_REQUEST', 'Permintaan Khusus')], max_length=20)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('request_date', models.DateField()),
                ('program', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('PREPARED', 'Disiapkan'), ('DISTRIBUTED', 'Terdistribusi'), ('REJECTED', 'Ditolak')], default='SUBMITTED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from uploaded proof document (Special Request)')),
            ],
            options={
                'db_table': 'distributions',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'distribution_items',
            },
        ),
    ]
