# Generated by Django 5.1.15 on 2026-02-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('items', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribution',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='items.facility'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='distribution.distribution'),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='items.item'),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Specific batch allocated (FEFO selection)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='stock.stock'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['status', 'request_date'], name='idx_dist_status_date'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['facility', 'request_date'], name='idx_dist_facility_date'),
        ),
    ]
