# Generated by Django 6.0.2 on 2026-03-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='document_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate (e.g., DIST-YYYYMM-XXXXX)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('PREPARED', 'Disiapkan'), ('DISTRIBUTED', 'Terdistribusi'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
    ]
