# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


def convert_allocation_children(apps, schema_editor):
    Distribution = apps.get_model('distribution', 'Distribution')
    allocation_children = Distribution.objects.filter(distribution_type='ALLOCATION')
    allocation_children.filter(status='GENERATED').update(
        distribution_type='SPECIAL_REQUEST',
        status='VERIFIED',
    )
    allocation_children.update(distribution_type='SPECIAL_REQUEST')


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_unit_price_precision'),
    ]

    operations = [
        migrations.RunPython(
            convert_allocation_children,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('LPLPO', 'LPLPO'), ('SPECIAL_REQUEST', 'Permintaan Khusus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis pada checkpoint workflow.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('PREPARED', 'Disiapkan'), ('DISTRIBUTED', 'Terdistribusi'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
    ]
