# Generated by Django 6.0.2 on 2026-03-04 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_program_model'),
        ('stock_opname', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopname',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Petugas yang ditugaskan untuk menghitung', related_name='assigned_stock_opnames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockopname',
            name='categories',
            field=models.ManyToManyField(help_text='Kategori barang yang akan dihitung', related_name='stock_opnames', to='items.category'),
        ),
    ]
