# Generated by Django 6.0.4 on 2026-06-24 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_opname', '0003_stockopnameitem_chk_actual_quantity_gte_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopnameitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockopnameitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
