# Generated by Django 6.0.8 on 2026-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_opname', '0011_backfill_completion_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockopname',
            name='document_number',
            field=models.CharField(blank=True, help_text='Diterbitkan otomatis saat stock opname dimulai.', max_length=100, null=True, unique=True),
        ),
    ]
