# Generated by Django 6.0.4 on 2026-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lplpoitem',
            name='procurement_source',
            field=models.CharField(blank=True, choices=[('BLUD', 'BLUD'), ('APBD', 'APBD'), ('BHP', 'BHP'), ('HIBAH', 'Hibah'), ('LAINNYA', 'Lainnya')], default='', help_text='Sumber pengadaan untuk item ini', max_length=20),
        ),
    ]
