# Generated by Django 6.0.4 on 2026-05-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0006_lplpo_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lplpoitem',
            name='pemakaian',
            field=models.PositiveIntegerField(default=0, help_text='Filled by Puskesmas operator'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='pembelian_puskesmas',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah pembelian mandiri Puskesmas pada periode ini'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='pemberian_jumlah',
            field=models.PositiveIntegerField(blank=True, help_text='Actual quantity given, system-suggested = jumlah_kebutuhan', null=True),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled from Distribution records, confirmable by Puskesmas'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='permintaan_jumlah',
            field=models.PositiveIntegerField(default=0, help_text='Requested quantity by Puskesmas'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='persediaan',
            field=models.PositiveIntegerField(default=0, help_text='stock_awal + penerimaan + pembelian_puskesmas'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='stock_awal',
            field=models.PositiveIntegerField(default=0, help_text='Manual on first LPLPO, auto-filled from previous month Stock Keseluruhan'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='stock_gudang_puskesmas',
            field=models.PositiveIntegerField(default=0, help_text='Physical count of Puskesmas warehouse stock'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='stock_keseluruhan',
            field=models.IntegerField(default=0, help_text='persediaan - pemakaian'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='waktu_kosong',
            field=models.PositiveSmallIntegerField(default=0, help_text='Stockout days in the reporting period'),
        ),
    ]
