# Generated by Django 6.0.4 on 2026-05-20 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_statuses(apps, schema_editor):
    LPLPO = apps.get_model("lplpo", "LPLPO")
    LPLPO.objects.filter(status="REJECTED").update(status="REJECTED_PUSKESMAS")
    for lplpo in LPLPO.objects.filter(
        status="REVIEWED",
        distribution_id__isnull=False,
    ).select_related("distribution"):
        lplpo.status = "APPROVED"
        if lplpo.approved_at is None and lplpo.distribution_id:
            lplpo.approved_at = lplpo.distribution.created_at
        if lplpo.approved_by_id is None and lplpo.distribution_id:
            lplpo.approved_by_id = lplpo.distribution.created_by_id
        lplpo.save(update_fields=["status", "approved_at", "approved_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0007_alter_lplpoitem_pemakaian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lplpo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lplpo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_lplpos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lplpo',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lplpo',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_lplpos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            migrate_legacy_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='lplpo',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('PIC_VERIFIED', 'Terverifikasi PIC'), ('REJECTED_PUSKESMAS', 'Ditolak ke Puskesmas'), ('REVIEWED', 'Ditinjau PIC'), ('REJECTED_PIC', 'Dikembalikan ke PIC'), ('APPROVED', 'Disetujui Kepala'), ('DISTRIBUTED', 'Didistribusikan'), ('CLOSED', 'Ditutup')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='jumlah_kebutuhan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='max(stock_optimum - stock_keseluruhan, 0) + waktu_kosong', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='stock_optimum',
            field=models.DecimalField(decimal_places=2, default=0, help_text='pemakaian * 1.2', max_digits=12),
        ),
    ]
