# Generated by Django 6.0.5 on 2026-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0008_lplpo_approved_at_lplpo_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lplpo',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('PIC_VERIFIED', 'Terverifikasi PIC'), ('REJECTED_PUSKESMAS', 'Ditolak ke Puskesmas'), ('REVIEWED', 'Ditinjau PIC'), ('REJECTED_PIC', 'Revisi Tinjauan PIC'), ('APPROVED', 'Siap Distribusi'), ('DISTRIBUTED', 'Didistribusikan'), ('CLOSED', 'Ditutup')], default='DRAFT', max_length=20),
        ),
    ]
