# Generated by Django 6.0.4 on 2026-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0009_alter_lplpo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lplpoitem',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Manual for January bootstrap; later periods auto-fill from distributed batch values or carry forward the previous month's price", max_digits=15),
        ),
    ]
