# Generated by Django 6.0.4 on 2026-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0012_remove_lplpoitem_pembelian_puskesmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled from same-month SBBK records, confirmable by Puskesmas'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan_auto_filled',
            field=models.BooleanField(default=False, help_text='True if penerimaan was auto-filled from same-month SBBK records'),
        ),
    ]
