# Generated by Django 6.0.4 on 2026-06-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0013_alter_lplpoitem_penerimaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled from same-month Puskesmas receipt confirmations, confirmable by Puskesmas'),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan_auto_filled',
            field=models.BooleanField(default=False, help_text='True if penerimaan was auto-filled from same-month Puskesmas receipt confirmations'),
        ),
    ]
