# Generated by Django 6.0.4 on 2026-06-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lplpo', '0014_alter_lplpoitem_penerimaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lplpoitem',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, help_text="January may be suggested from same-month confirmed receipt confirmations; later periods use same-month weighted-average receipt prices or carry forward the previous month's price", max_digits=15),
        ),
        migrations.AlterField(
            model_name='lplpoitem',
            name='penerimaan',
            field=models.PositiveIntegerField(default=0, help_text='Auto-suggested from same-month Puskesmas receipt confirmations when available, confirmable by Puskesmas'),
        ),
    ]
