# Generated by Django 6.0.2 on 2026-02-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_controlled',
        ),
    ]
