# Generated by Django 6.0.2 on 2026-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_program_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('PUSKESMAS', 'Puskesmas'), ('RS', 'Rumah Sakit'), ('CLINIC', 'Klinik'), ('LABORATORIUM', 'Laboratorium')], default='PUSKESMAS', max_length=20),
        ),
    ]
