# Generated by Django 6.0.4 on 2026-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_is_essential'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Therapeutic Class',
                'verbose_name_plural': 'Therapeutic Classes',
                'db_table': 'therapeutic_classes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='therapeutic_classes',
            field=models.ManyToManyField(blank=True, help_text='Drug therapeutic groups used for reporting.', related_name='items', to='items.therapeuticclass'),
        ),
    ]
