# Generated by Django 6.0.4 on 2026-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_therapeuticclass_item_therapeutic_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_expiry_date',
            field=models.BooleanField(default=True, help_text='Whether stock batches for this item are expected to carry an expiry date.'),
        ),
    ]
