# Generated by Django 6.0.7 on 2026-07-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_backfill_non_expiring_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
